spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/monew
    username: monew_user
    password: monew_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
        show_sql: false
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: info
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api-docs.html
    display-request-duration: true
    enabled: true
  api-docs:
    path: /api-docs

info:
  app:
    name: monew
    description: News Web Application
    version: 1.0.0
    encoding: UTF-8
    java-version: 17

  company:
    name: sprintTeam3
    email: genius5375@gmail.com

logging:
  file:
    path: /app/logs

management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}