name: integration test

on:
  pull_request:
    branches: [develop]

  push:
    branches: [release]

jobs:
  build:
    name: IntegrationTest
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      AWS_S3_ACCESS_KEY: ${{secrets.AWS_S3_ACCESS_KEY}}
      AWS_S3_SECRET_KEY: ${{secrets.AWS_S3_SECRET_KEY}}
      AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
      MONGODB_CONNECTION_URL: ${{secrets.MONGODB_CONNECTION_URL}}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: monew
          POSTGRES_USER: monew_user
          POSTGRES_PASSWORD: monew_password
        options: >-
          --health-cmd="pg_isready -U monew_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check PostgreSQL connection
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql -h localhost -U monew_user -d monew -c '\dt'
        env:
          PGPASSWORD: monew_password

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run integration test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/monew
          SPRING_DATASOURCE_USERNAME: monew_user
          SPRING_DATASOURCE_PASSWORD: monew_password
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
        run: ./gradlew test

      - name: Upload jacoco report to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          min-coverage-overall: 40
